# Generated by Django 5.2 on 2026-04-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurgicalGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_implant_company', models.CharField(blank=True, max_length=255, null=True)),
                ('implant_name', models.CharField(blank=True, max_length=255, null=True)),
                ('jaw_information', models.JSONField(blank=True, null=True)),
                ('prosthetic_plan', models.TextField(blank=True, null=True)),
                ('desired_implant_location', models.CharField(blank=True, max_length=255, null=True)),
                ('preferred_size', models.CharField(blank=True, max_length=255, null=True)),
                ('ap_spread_angle_implant', models.CharField(blank=True, max_length=255, null=True)),
                ('immediate_extractions', models.BooleanField(blank=True, null=True)),
                ('immediate_extractions_notes', models.CharField(blank=True, max_length=255, null=True)),
                ('bone_grafting', models.BooleanField(blank=True, null=True)),
                ('bone_grafting_notes', models.CharField(blank=True, max_length=255, null=True)),
                ('bone_reduction', models.BooleanField(blank=True, null=True)),
                ('bone_reduction_notes', models.CharField(blank=True, max_length=255, null=True)),
                ('surgical_drill_kit', models.CharField(blank=True, max_length=255, null=True)),
                ('provisional_planning', models.TextField(blank=True, null=True)),
                ('surgery_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
