# Generated by Django 5.2 on 2026-04-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surgical_guide', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surgicalguide',
            name='jaw_information',
            field=models.CharField(blank=True, choices=[('maxilla', 'Maxilla'), ('mandible', 'Mandible')], max_length=20, null=True),
        ),
    ]
