# Generated by Django 5.2 on 2026-04-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surgical_guide', '0002_alter_surgicalguide_jaw_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surgicalguide',
            name='jaw_information',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
