# Generated by Django 5.2 on 2026-04-11 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surgical_guide', '0003_alter_surgicalguide_jaw_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='surgicalguide',
            name='pdf_document',
            field=models.FileField(blank=True, null=True, upload_to='surgical_implant_form/'),
        ),
    ]
