# Generated by Django 5.2 on 2026-04-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surgical_guide', '0004_surgicalguide_pdf_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='surgicalguide',
            name='contact_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='surgicalguide',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='surgicalguide',
            name='patient_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
