# Generated by Django 5.2 on 2026-04-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surgical_guide', '0005_surgicalguide_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surgicalguide',
            name='contact_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
