# Generated by Django 5.2 on 2026-06-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surgical_guide', '0006_alter_surgicalguide_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surgicalguide',
            name='contact_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
