# Generated by Django 5.2 on 2025-08-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0022_alter_stlfiledata_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='city',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
