# Generated by Django 5.2 on 2025-09-12 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0023_contact_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-date']},
        ),
    ]
