# Generated by Django 5.2 on 2026-03-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0026_contact_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
