# Generated by Django 3.2 on 2023-07-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20230114_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeforeAfter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=156)),
                ('image', models.ImageField(upload_to='SEO')),
            ],
        ),
    ]
