# Generated by Django 3.2 on 2023-07-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_events_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonials',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, to='blog.Product'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='canonical',
            field=models.CharField(default='https://advancedentalexport.com/', max_length=900),
        ),
        migrations.AlterField(
            model_name='category',
            name='canonical',
            field=models.CharField(default='https://advancedentalexport.com/', max_length=900),
        ),
        migrations.AlterField(
            model_name='product',
            name='canonical',
            field=models.CharField(default='https://advancedentalexport.com/', max_length=900),
        ),
    ]
