# Generated by Django 3.2 on 2024-02-26 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='schema',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='schema',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='schema',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subproduct',
            name='schema',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='schema',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testimonials',
            name='schema',
            field=models.TextField(blank=True, null=True),
        ),
    ]
