# Generated by Django 3.2 on 2024-02-26 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_auto_20240226_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='schema',
            field=models.TextField(blank=True, null=True),
        ),
    ]
