# Generated by Django 3.2 on 2024-04-08 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_auto_20240226_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=156)),
                ('contact', models.CharField(max_length=156)),
                ('order', models.IntegerField(default=2)),
            ],
        ),
    ]
