# Generated by Django 3.2 on 2024-04-08 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_doctor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doctor',
            new_name='ContactDetails',
        ),
    ]
