# Generated by Django 5.1.3 on 2025-01-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_rename_doctor_contactdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(max_length=255)),
                ('meta_description', models.TextField()),
                ('canonical_link', models.URLField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='web_stories/images/')),
                ('video', models.FileField(upload_to='web_stories/videos/')),
                ('author', models.CharField(max_length=100)),
                ('publish_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
