# Generated by Django 5.1.3 on 2025-01-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_webstory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webstory',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='webstory',
            name='image',
            field=models.ImageField(upload_to='SEO/images/'),
        ),
        migrations.AlterField(
            model_name='webstory',
            name='video',
            field=models.FileField(upload_to='SEO/videos/'),
        ),
    ]
