# Generated by Django 5.1.3 on 2025-01-29 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0039_remove_webstory_created_at_alter_webstory_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webstory',
            name='video',
        ),
        migrations.CreateModel(
            name='WebStoryVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='SEO/videos/')),
                ('web_story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='blog.webstory')),
            ],
        ),
    ]
