# Generated by Django 5.1.3 on 2025-01-29 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0040_remove_webstory_video_webstoryvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='webstory',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
