# Generated by Django 5.1.3 on 2025-01-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0041_webstory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='webstory',
            name='links',
            field=models.TextField(blank=True, null=True),
        ),
    ]
