# Generated by Django 5.1.3 on 2025-02-22 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0042_webstory_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='webstory',
            name='links',
            field=models.URLField(blank=True, null=True),
        ),
    ]
