# Generated by Django 5.1.3 on 2025-02-28 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0043_events_meta_description_alter_webstory_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewEventLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=156)),
                ('location', models.CharField(max_length=156)),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='thumbnails/')),
                ('social_links', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
