# Generated by Django 5.1.3 on 2025-02-28 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0044_neweventlink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neweventlink',
            old_name='location',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='neweventlink',
            old_name='date',
            new_name='end_date',
        ),
        migrations.RemoveField(
            model_name='neweventlink',
            name='image',
        ),
        migrations.AddField(
            model_name='neweventlink',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
        migrations.AddField(
            model_name='neweventlink',
            name='skyline_image',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
        migrations.AddField(
            model_name='neweventlink',
            name='start_date',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='neweventlink',
            name='social_links',
            field=models.URLField(default='https://example.com'),
            preserve_default=False,
        ),
    ]
