# Generated by Django 5.1.3 on 2025-05-15 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0045_rename_location_neweventlink_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='keyword',
            new_name='h1',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='description',
            new_name='meta_description',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='meta_title',
        ),
        migrations.AlterField(
            model_name='category',
            name='canonical',
            field=models.CharField(default='https://advancedentalexport.com/{{ slug }}', max_length=900, null=True),
        ),
    ]
