# Generated by Django 5.1.3 on 2025-05-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0046_rename_keyword_category_h1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='canonical',
            field=models.CharField(default='https://advancedentalexport.com/', max_length=900),
        ),
    ]
