# Generated by Django 5.2 on 2025-05-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0047_alter_category_canonical'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='blog.tags'),
        ),
    ]
