# Generated by Django 5.2 on 2025-07-08 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0049_product_category_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='type',
            field=models.CharField(choices=[('city', 'City'), ('state', 'State')], default='city', max_length=10),
        ),
    ]
