# Generated by Django 5.2 on 2025-08-11 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0050_place_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='alt',
            field=models.CharField(blank=True, max_length=156, null=True),
        ),
    ]
