# Generated by Django 5.2 on 2025-08-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0051_blog_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='canonical',
            field=models.CharField(default='https://advancedentalexport.com/blog/', max_length=900),
        ),
        migrations.AlterField(
            model_name='blog',
            name='og_site',
            field=models.CharField(default='https://advancedentalexport.com/', max_length=156),
        ),
    ]
