# Generated by Django 5.2 on 2025-08-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0052_alter_blog_canonical_alter_blog_og_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='alt',
            field=models.CharField(blank=True, max_length=156, null=True),
        ),
        migrations.AddField(
            model_name='eventsgallery',
            name='alt',
            field=models.CharField(blank=True, max_length=156, null=True),
        ),
    ]
