# Generated by Django 5.2 on 2025-08-15 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0053_events_alt_eventsgallery_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='alt',
            field=models.CharField(blank=True, max_length=156, null=True),
        ),
    ]
