# Generated by Django 5.2 on 2025-08-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0054_gallery_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='beforeafter',
            name='alt',
            field=models.CharField(blank=True, max_length=156, null=True),
        ),
    ]
