# Generated by Django 5.2 on 2025-08-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0055_beforeafter_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutimage',
            name='alt',
            field=models.CharField(blank=True, max_length=156, null=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='alt',
            field=models.CharField(blank=True, max_length=156, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='alt',
            field=models.CharField(blank=True, max_length=156, null=True),
        ),
    ]
