# Generated by Django 5.2 on 2025-08-15 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0056_aboutimage_alt_aboutpage_alt_client_alt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='alt',
        ),
    ]
