# Generated by Django 5.2 on 2025-08-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0057_remove_aboutpage_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='alt',
            field=models.CharField(blank=True, max_length=156, null=True),
        ),
        migrations.AddField(
            model_name='webstory',
            name='alt',
            field=models.CharField(blank=True, max_length=156, null=True),
        ),
    ]
