# Generated by Django 5.2 on 2025-08-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0058_team_alt_webstory_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='alt',
            field=models.CharField(blank=True, max_length=156, null=True),
        ),
    ]
