# Generated by Django 5.2 on 2025-12-26 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0059_product_alt'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='testimonials',
        #     name='position',
        # ),
        # migrations.RemoveField(
        #     model_name='testimonials',
        #     name='product',
        # ),
        # migrations.AddField(
        #     model_name='testimonials',
        #     name='google_review_link',
        #     field=models.CharField(blank=True, max_length=1256, null=True),
        # ),
        migrations.AddField(
            model_name='testimonials',
            name='priority',
            field=models.BooleanField(default=False, help_text='Priority testimonial (Yes / No)'),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='SEO'),
        ),
    ]
