# Generated by Django 5.2 on 2025-12-26 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0060_remove_testimonials_position_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='testimonials',
        #     name='position',
        # ),
        # migrations.RemoveField(
        #     model_name='testimonials',
        #     name='product',
        # ),
        migrations.AddField(
            model_name='testimonials',
            name='google_review_link',
            field=models.CharField(blank=True, max_length=1256, null=True),
        ),
    ]
