# Generated by Django 5.2.6 on 2025-12-29 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0061_remove_testimonials_position_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonials',
            name='position',
        ),
        migrations.RemoveField(
            model_name='testimonials',
            name='product',
        ),
    ]
