# Generated by Django 5.2 on 2026-02-13 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0062_remove_testimonials_position_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['display_order']},
        ),
        migrations.AddField(
            model_name='team',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
