# Generated by Django 5.2 on 2026-03-10 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0063_alter_team_options_team_display_order'),
    ]

    # operations = [
    #     migrations.RemoveField(
    #         model_name='testimonials',
    #         name='position',
    #     ),
    #     migrations.RemoveField(
    #         model_name='testimonials',
    #         name='product',
    #     ),
    # ]
