# Generated by Django 5.2 on 2026-03-10 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0065_remove_testimonials_position_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonials',
            name='position',
        ),
        # migrations.RemoveField(
        #     model_name='testimonials',
        #     name='product',
        # ),
    ]
