# Generated by Django 5.2 on 2026-03-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0066_remove_testimonials_position_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Image Usage Search',
                'verbose_name_plural': 'Image Usage Search',
                'managed': False,
            },
        ),
        # migrations.RemoveField(
        #     model_name='testimonials',
        #     name='product',
        # ),
    ]
