# Generated by Django 5.2 on 2026-04-07 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0067_imagesearch_remove_testimonials_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonials',
            name='product',
        ),
    ]
