# Generated by Django 5.2 on 2026-04-07 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0068_remove_testimonials_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='award/')),
                ('alt', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
