# Generated by Django 5.2 on 2026-04-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0069_award'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='SEO')),
                ('name', models.CharField(max_length=156)),
                ('review', models.TextField()),
                ('google_review_link', models.CharField(blank=True, max_length=1256, null=True)),
                ('priority', models.BooleanField(default=False, help_text='Priority Review (Yes / No)')),
            ],
        ),
    ]
