# Generated by Django 5.2 on 2026-04-15 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0070_review'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='DoctorReview',
        ),
    ]
