# Generated by Django 6.0.4 on 2026-07-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0071_rename_review_doctorreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='SEO/Prosthetic_gallery'),
        ),
    ]
