# Generated by Django 6.0.4 on 2026-09-29 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0072_alter_gallery_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedirectRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_url', models.CharField(help_text='Old URL path to redirect from (e.g. /old-page/ or old-page)', max_length=500, unique=True)),
                ('new_url', models.CharField(help_text='New URL path or full URL to redirect to (e.g. /new-page/ or https://example.com/new-page)', max_length=500)),
                ('is_active', models.BooleanField(default=True, help_text='Enable or disable this 301 redirect rule')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '301 Redirect Rule',
                'verbose_name_plural': '301 Redirect Rules',
                'ordering': ['-created_at'],
            },
        ),
    ]
